[workspace]
members = [
    "emscripten_em_js",
    "remglk",
    "remglk_capi",
]
resolver = "2"

[profile.release]
lto = true

[profile.dev-wasm]
inherits = "dev"
panic = "abort"

[profile.release-wasm]
inherits = "release"
panic = "abort"