name: build-and-test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update
      - run: cargo build
      - run: cargo clippy
      - run: ./tests/prepare.sh glulxe regtest
      - run: ./tests/runtests.sh